# Site settings
title:          = Findings
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "https://varanasikalyan.github.io/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Fed Express
  url:          https://github.com/varanasikalyan/varanasikalyan.github.io
  email:        varanasikalyan@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, findings.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-findings

theme:      findings

permalink:  /:year-:month-:day/:title
paginate:   5
